### ISSUE TITLE
Allow alpha in range 0-255

### ISSUE THREAD

**Issue by The-Force** [Denis-net/json-colors#1]
I'm currently editing a theme.json for Cura, a 3D printer slicing application, it uses rgba arrays with byte values (0-255) for each component, alpha included. 

e.g.: "main_background": [39, 44, 48, 255],

Would be nice to have support for it.

**Comment by Denis-net** [comment]
Hey @The-Force ! 😄👋🏼

Wow, it's a really nice toy ! 👏🏼👍🏼
I haven't explored the 3D printer word yet, but one day i would like to give it a try (or the resin printers).
Out of curiosity: Do you have purchased one for job or for hobby ?
Do you have already printed your first robot's parts ?😜

For the feature : it should be available in a few minutes ! 👍🏼

**Comment by The-Force** [comment]
> Out of curiosity: Do you have purchased one for job or for hobby ?

I only have one currently but I'm planning on building a second. I like to build and mod it as a hobby but I have done some work with it too.

> Do you have already printed your first robot's parts ?

I'm not into robots, I mean, I like them but I don't have enough interest to build one without a purpose.

> For the feature : it should be available in a few minutes !

Nice, thank you very much!

**Comment by Denis-net** [comment]
> I only have one currently but I'm planning on building a second. I like to build and mod it as a hobby but I have done some work with it too.

Cool !

> I'm not into robots, I mean, I like them but I don't have enough interest to build one without a purpose.

Understandable;
If I can: what have you accomplished so far?

> Nice, thank you very much!

Fancy that !

Thanks for having tried my extension 😊✌🏼
